import './App.css.proxy.js';
/* src/App.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import Router from "../web_modules/svelte-spa-router.js";
import { wrap } from "../web_modules/svelte-spa-router/wrap.js";
import AppBar from "./components/AppBar.js";
import Loading from "./components/Loading.js";
import Home from "./pages/Home.js";

function create_fragment(ctx) {
	let appbar;
	let t;
	let main;
	let router;
	let current;
	appbar = new AppBar({});
	router = new Router({ props: { routes: /*routes*/ ctx[0] } });

	return {
		c() {
			create_component(appbar.$$.fragment);
			t = space();
			main = element("main");
			create_component(router.$$.fragment);
		},
		m(target, anchor) {
			mount_component(appbar, target, anchor);
			insert(target, t, anchor);
			insert(target, main, anchor);
			mount_component(router, main, null);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(appbar.$$.fragment, local);
			transition_in(router.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(appbar.$$.fragment, local);
			transition_out(router.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(appbar, detaching);
			if (detaching) detach(t);
			if (detaching) detach(main);
			destroy_component(router);
		}
	};
}

function instance($$self) {
	

	const routes = {
		"/": Home,
		"/page2": wrap({
			asyncComponent: () => import("./pages/Page2.js"),
			loadingComponent: Loading
		}),
		"/page3": wrap({
			asyncComponent: () => import("./pages/Page3.js"),
			loadingComponent: Loading
		}),
		"/test": Loading
	};

	return [routes];
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default App;