import './Page2.css.proxy.js';
/* src/pages/Page2.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	add_render_callback,
	append,
	attr,
	create_in_transition,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from "../../web_modules/svelte/internal.js";

import { fade } from "../../web_modules/svelte/transition.js";
import src from "../assets/svelte-horizontal.png.proxy.js";

function create_fragment(ctx) {
	let div;
	let h2;
	let t1;
	let span;
	let img;
	let img_src_value;
	let t2;
	let div_intro;

	return {
		c() {
			div = element("div");
			h2 = element("h2");
			h2.textContent = "very good page 2";
			t1 = space();
			span = element("span");
			img = element("img");
			t2 = text(" is the best");
			if (img.src !== (img_src_value = src)) attr(img, "src", img_src_value);
			attr(img, "alt", "very good svelte logo");
			attr(img, "class", "svelte-cq42uk");
			attr(span, "class", "svelte-cq42uk");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, h2);
			append(div, t1);
			append(div, span);
			append(span, img);
			append(span, t2);
		},
		p: noop,
		i(local) {
			if (!div_intro) {
				add_render_callback(() => {
					div_intro = create_in_transition(div, fade, { duration: 100 });
					div_intro.start();
				});
			}
		},
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

class Page2 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Page2;