import './AppBar.css.proxy.js';
/* src/components/AppBar.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	action_destroyer,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	run_all,
	safe_not_equal,
	space
} from "../../web_modules/svelte/internal.js";

import active from "../../web_modules/svelte-spa-router/active.js";

function create_fragment(ctx) {
	let nav;
	let span;
	let t1;
	let a0;
	let active_action;
	let t3;
	let a1;
	let active_action_1;
	let t5;
	let a2;
	let active_action_2;
	let mounted;
	let dispose;

	return {
		c() {
			nav = element("nav");
			span = element("span");
			span.textContent = "epic template";
			t1 = space();
			a0 = element("a");
			a0.textContent = "Home";
			t3 = space();
			a1 = element("a");
			a1.textContent = "Page 2";
			t5 = space();
			a2 = element("a");
			a2.textContent = "Page 3";
			attr(span, "class", "svelte-qnztx");
			attr(a0, "href", "#/");
			attr(a0, "class", "svelte-qnztx");
			attr(a1, "href", "#/page2");
			attr(a1, "class", "svelte-qnztx");
			attr(a2, "href", "#/page3");
			attr(a2, "class", "svelte-qnztx");
			attr(nav, "class", "svelte-qnztx");
		},
		m(target, anchor) {
			insert(target, nav, anchor);
			append(nav, span);
			append(nav, t1);
			append(nav, a0);
			append(nav, t3);
			append(nav, a1);
			append(nav, t5);
			append(nav, a2);

			if (!mounted) {
				dispose = [
					action_destroyer(active_action = active.call(null, a0)),
					action_destroyer(active_action_1 = active.call(null, a1)),
					action_destroyer(active_action_2 = active.call(null, a2))
				];

				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(nav);
			mounted = false;
			run_all(dispose);
		}
	};
}

class AppBar extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default AppBar;