import './Loading.css.proxy.js';
/* src/components/Loading.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	add_render_callback,
	attr,
	create_in_transition,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../web_modules/svelte/internal.js";

import { fade } from "../../web_modules/svelte/transition.js";

function create_fragment(ctx) {
	let div2;
	let div2_intro;

	return {
		c() {
			div2 = element("div");
			div2.innerHTML = `<div class="spinner svelte-1ilml2y"><div class="spinner-animation svelte-1ilml2y"><svg class="spinner-svg svelte-1ilml2y" width="50" height="50" stroke-width="8.00" viewBox="1.00 1.00 98.00 98.00"><path class="spinner-track svelte-1ilml2y" d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90"></path><path class="spinner-head svelte-1ilml2y" d="M 50,50 m 0,-45 a 45,45 0 1 1 0,90 a 45,45 0 1 1 0,-90" pathLength="280" stroke-dasharray="280 280" stroke-dashoffset="210"></path></svg></div></div>`;
			attr(div2, "class", "loading-wrapper svelte-1ilml2y");
		},
		m(target, anchor) {
			insert(target, div2, anchor);
		},
		p: noop,
		i(local) {
			if (!div2_intro) {
				add_render_callback(() => {
					div2_intro = create_in_transition(div2, fade, { duration: 100 });
					div2_intro.start();
				});
			}
		},
		o: noop,
		d(detaching) {
			if (detaching) detach(div2);
		}
	};
}

class Loading extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Loading;